name: widgetbook_theme_builder
description: "Cherry UI widgetbook"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cherry_ui:
    path: ..
  code_highlight_view: ^0.1.1
  flame: ^1.30.1
  flutter:
    sdk: flutter
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0

dev_dependencies:
  build_runner: ^2.7.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
  widgetbook_generator: ^3.16.0

flutter:
  uses-material-design: true
